Multiple notifications fix
remp2020/crm-gopay-module pull request #7
Opened 2020-12-02 07:34 UTC by mikoczy

This week there were some problems at the payment gateway, and they sent the same notification a couple times to the notification endpoint (what can teoretically happen for various reasons any time - server problems, etc.), and we had dozens of active recurrent payments created. So I've added a check for this to the notification method. Sometimes instead of payment data, the gateway sends an error response to the status request, that is handled in this pr too.

2020-12-02 10:10 UTC, rootpd requested changes

2020-12-02 10:10 UTC, rootpd commented on src/gateways/GoPayRecurrent.php
> +                    $id
This doesn't look good, there's no `$id` variable.

2020-12-02 10:10 UTC, rootpd commented on src/gateways/GoPayRecurrent.php
> +        return true;
By explicitly checking `$data['state']` values above, there's a chance you might miss some unhandled status.

- At this point the handler doesn't do anything with `self::STATE_CREATED`. If it's correct behavior, I'd probably explicitly handle that state with its own `if` branch and call `return true`. As a reader, I'd have a clear idea that it's intentional.
- Basically each of those `if` branches checking `$data['state']` should probably end with `return` statement. There's no need to continue if the payment was already handled.
- If we get here, to the default `return true` at the end of method, it means that the notification contained a state that we didn't handle. I'd probably want to fail fast here and throw an exception with `unhandled state: $data['state]` message.

2020-12-02 14:53 UTC, mikoczy commented
thanks for the review, I've changed it, take a look please..

2020-12-04 08:04 UTC, rootpd commented
Merged via https://github.com/remp2020/crm-gopay-module/commit/f1779228ada469af5787d13ac00c0d7b100af0b3.

2020-12-04 08:04 UTC, closed without merging